# vim:ft=conf

shell /bin/zsh

shell_integration no-cursor
# Font settings
font_size 20.5

disable_ligatures never
# modify_font cell_width 80%
modify_font cell_height 90%
modify_font baseline 3

# Cursor settings
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.15
cursor_shape underline
cursor_blink_interval -1
# Window decorations
# Set to "no" to display a top bar for dragging and moving the window
# Use "smart" to hide decorations when maximized but show in windowed mode
hide_window_decorations titlebar-only
window_margin_width 0
window_padding_width 0
# Miscellaneous settings
# Enable option key as Alt on macOS
macos_option_as_alt yes
# Set scrollback lines maximum
scrollback_lines 1000000

# Copy on select
# Automatically copy text to the clipboard when selected
copy_on_select yes

include moon.conf


# BEGIN_KITTY_FONTS
font_family      family="Operator Mono SSm Lig" style="book" features="+liga +ss11 +ss12"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#
#
# BEGIN_KITTY_SYMBOL_MAPS
symbol_map U+23FB-U+23FE,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+E0D6-U+E0D7,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B8,U+E700-U+E8EF,U+EA60-U+EA88,U+EA8A-U+EA8C,U+EA8F-U+EAC7,U+EAC9,U+EACC-U+EB09,U+EB0B-U+EB4E,U+EB50-U+EC1E,U+ED00-U+EFCE,U+F000-U+F381,U+F400-U+F533,U+F0001-U+F1AF0 Symbols Nerd Font
symbol_map U+2E80-U+2FDF,U+3000-U+303F,U+31C0-U+31EF,U+3400-U+4DBF,U+4E00-U+9FFF,U+F900-U+FAFF,U+FE30-U+FE4F,U+FF00-U+FFEF,U+20000-U+2A6DF,U+2A700-U+2EE5F,U+30000-U+323AF Maple Mono NF CN
symbol_map U+2713-U+2715,U+2717-U+2718 FiraCode Nerd Font
symbol_map U+2300-U+23FF,U+2600-U+2712,U+2716,U+2719-U+27BF,U+FE0F,U+1F000-U+1FAFF Apple Color Emoji
# END_KITTY_SYMBOL_MAPS
