vim.pack.add({
  "https://github.com/arborist-ts/arborist.nvim",
})

require("arborist").setup({
  prefer_wasm = false,
  update_cadence = "daily",
  ensure_installed = {
    "bash",
    "c",
    "diff",
    "html",
    "javascript",
    "jsdoc",
    "json",
    "lua",
    "luadoc",
    "luap",
    "markdown",
    "markdown_inline",
    "printf",
    "python",
    "query",
    "regex",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
    "git_config",
    "gitcommit",
    "git_rebase",
    "gitignore",
    "gitattributes",
    "typst",
    "go",
    "rust",
    "java",
    "javadoc",
  },
  overrides = {},
})
