# Setting up the Path
set -e fish_user_paths

## ADD to PATH ##
# Homebrew generated by `brew shellenv`
set -gx HOMEBREW_PREFIX /opt/homebrew
set -gx HOMEBREW_CELLAR /opt/homebrew/Cellar
set -gx HOMEBREW_REPOSITORY /opt/homebrew
set -q PATH; or set PATH ''
set -gx PATH /opt/homebrew/bin /opt/homebrew/sbin $PATH
set -q MANPATH; or set MANPATH ''
set -gx MANPATH /opt/homebrew/share/man $MANPATH
set -q INFOPATH; or set INFOPATH ''
set -gx INFOPATH /opt/homebrew/share/info $INFOPATH

#set -U fish_user_paths "/usr/local/sbin" $fish_user_paths # homebrew - Intel
set -g fish_user_paths $HOMEBREW_PREFIX/bin $fish_user_paths # homebrew ARM

# GO
set -x GOPATH $HOME/.go
set -x PATH $PATH $GOPATH/bin

# Rust
set -g fish_user_paths $HOME/.cargo/bin $fish_user_paths


# FZF and FD helpers for NeoVim
set -x FZF_DEFAULT_COMMAND "fd --type f"
set -x FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"


