local M = {}

M.icons = {
  lazy_kind_icons = {
    Array = "",
    Boolean = "󰨙",
    Class = "",
    Codeium = "󰘦",
    Color = "",
    Control = "",
    Collapsed = "",
    Constant = "󰏿",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "󰊕",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "󰊕",
    Module = "",
    Namespace = "󰦮",
    Null = "",
    Number = "󰎠",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "󱄽",
    String = "",
    Struct = "󰆼",
    Supermaven = "",
    TabNine = "󰏚",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "󰀫",
  },
  lspkind_kind_icons = {
    String = "",
    Object = "",
    Array = "",
    Boolean = "󰨙",
    Text = "󰉿",
    Number = "󰎠",
    Method = "",
    Function = "󰊕",
    Constructor = "",
    -- Field = "󰜢",
    Field = "",
    Variable = "",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Namespace = "󰦮",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "󱄽",
    Color = "󰏘",
    File = "󰈙",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "",
    Codeium = "󰚩",
    Copilot = "",
    Control = "",
    Collapsed = "",
    Component = "󰅴",
    Fragment = "󰩦",
    Key = "",
    Macro = "󰁥",
    Null = "",
    Package = "",
    Parameter = "",
    StaticMethod = "󰰑",
    TypeAlias = "",
  },
  misc = {
    dots = "󰇘",
    bug = "",
    dashed_bar = "┊",
    ellipsis = "…",
    git = "",
    palette = "󰏘",
    robot = "󰚩",
    search = "",
    terminal = "",
    toolbox = "󰦬",
    vertical_bar = "│",
  },
  ft = {
    octo = "",
  },
  dap = {
    Stopped = { "󰁕", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = "",
    BreakpointCondition = "",
    BreakpointRejected = { "", "DiagnosticError" },
    LogPoint = ".>",
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
}

M.snacks_layout = {
  sidebar = {
    preview = "main",
    layout = {
      backdrop = false,
      width = math.floor(vim.o.columns * 0.2),
      min_width = math.floor(vim.o.columns * 0.2),
      height = 0,
      position = "left",
      border = "none",
      box = "vertical",
      {
        win = "input",
        height = 1,
        border = true,
        title = "{title} {live} {flags}",
        title_pos = "center",
      },
      { win = "list", border = "none" },
      { win = "preview", title = "{preview}", height = 0.4, border = "top" },
    },
  },
  vscode = {
    hidden = { "preview" },
    layout = {
      backdrop = false,
      row = -1,
      -- width = 1,
      height = 0.3,
      min_width = 80,
      border = "none",
      box = "vertical",
      { win = "preview", title = "{preview}", height = 0.5, border = "single" },
      {
        box = "vertical",
        border = "none",
        title = "{title} {live} {flags}",
        title_pos = "center",
        { win = "input", height = 1, border = "bottom" },
        { win = "list", border = "none" },
      },
    },
  },
  ivy = {
    hidden = { "preview" },
    layout = {
      box = "vertical",
      backdrop = false,
      row = -1,
      width = 0,
      height = 0.3,
      border = "none",
      title = " {title} {live} {flags}",
      title_pos = "left",
      { win = "input", height = 1, border = "none" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
        { win = "preview", title = "{preview}", width = 0.6, border = "left" },
      },
    },
  },
  minibuffer = {
    hidden = { "preview" },
    layout = {
      box = "vertical",
      backdrop = false,
      row = -1,
      width = 0,
      height = 0.4,
      border = "none",
      relative = "minibuffer",
      use_minibuffer = true,
      -- { win = "input", height = 1, border = "none" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
      },
    },
  },
  ivy_split = {
    preview = "main",
    layout = {
      box = "vertical",
      backdrop = false,
      width = 0,
      height = 0.4,
      position = "bottom",
      border = "top",
      title = " {title} {live} {flags}",
      title_pos = "left",
      { win = "input", height = 1, border = "bottom" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
        { win = "preview", title = "{preview}", width = 0.6, border = "left" },
      },
    },
  },
}

return M
