local M = {}

M.layout = {
  dropdown_pick = {
    layout = {
      backdrop = true,
      row = -1,
      width = 0.9,
      min_width = 80,
      border = "none",
      box = "vertical",
      { win = "preview", title = "{preview}", height = 0.45, border = "rounded" },
      {
        box = "vertical",
        border = "rounded",
        title = "{title} {live} {flags}",
        title_pos = "left",
        { win = "input", height = 1, border = "none" },
        { win = "list", border = "rounded" },
      },
    },
  },
  vscode = {
    hidden = { "preview" },
    layout = {
      backdrop = false,
      row = -1,
      width = 0.5,
      min_width = 80,
      height = 0.4,
      border = "none",
      box = "vertical",
      { win = "input", height = 1, border = true, title = "{title} {live} {flags}", title_pos = "center" },
      { win = "list", border = "hpad" },
      { win = "preview", title = "{preview}", border = true },
    },
  },
  right = {
    preview = "main",
    layout = {
      backdrop = false,
      width = 40,
      min_width = 40,
      height = 0,
      position = "right",
      border = "none",
      box = "vertical",
      {
        win = "input",
        height = 1,
        border = true,
        title = "{title} {live} {flags}",
        title_pos = "center",
      },
      { win = "list", border = "none" },
      { win = "preview", title = "{preview}", height = 0.4, border = "top" },
    },
  },
}

M.icons = {
  mini_kind_icons = {
    Codeium = "󰚩",
    Copilot = "",
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    Enummember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    ["Function"] = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    Typeparameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  lazy_kind_icons = {
    Array = "",
    Boolean = "󰨙",
    Class = "",
    Codeium = "󰘦",
    Color = "",
    Control = "",
    Collapsed = "",
    Constant = "󰏿",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "󰊕",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "󰊕",
    Module = "",
    Namespace = "󰦮",
    Null = "",
    Number = "󰎠",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "󱄽",
    String = "",
    Struct = "󰆼",
    Supermaven = "",
    TabNine = "󰏚",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "󰀫",
  },
  lspkind_kind_icons = {
    String = "",
    Object = "",
    Array = "",
    Boolean = "󰨙",
    Text = "󰉿",
    Number = "󰎠",
    Method = "",
    Function = "󰊕",
    Constructor = "",
    -- Field = "󰜢",
    Field = "",
    Variable = "",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Namespace = "󰦮",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "󱄽",
    Color = "󰏘",
    File = "󰈙",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "",
    Codeium = "󰚩",
    Copilot = "",
    Control = "",
    Collapsed = "",
    Component = "󰅴",
    Fragment = "󰩦",
    Key = "",
    Macro = "󰁥",
    Null = "",
    Package = "",
    Parameter = "",
    StaticMethod = "󰰑",
    TypeAlias = "",
  },
  misc = {
    dots = "󰇘",
    bug = "",
    dashed_bar = "┊",
    ellipsis = "…",
    git = "",
    palette = "󰏘",
    robot = "󰚩",
    search = "",
    terminal = "",
    toolbox = "󰦬",
    vertical_bar = "│",
  },
  ft = {
    octo = "",
  },
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
}
M.blink = {
  menu = {
    border = {
      { "󱐋", "WarningMsg" },
      "─",
      "╮",
      "│",
      "╯",
      "─",
      "╰",
      "│",
    },
  },
  documention = {
    border = {
      { "", "DiagnosticHint" },
      "─",
      "╮",
      "│",
      "╯",
      "─",
      "╰",
      "│",
    },
  },
}
return M
