local M = {}
M.mode_colors = {
  bg = "#3c3836", -- "#000000",
  copy = "#f1ff5e",
  delete = "#ff6e5e",
  change = "#ff6e5e", -- Optional param, defaults to delete
  format = "#c79585",
  insert = "#5eff6c",
  replace = "#ff5ea0",
  select = "#ff5ef1", -- Optional param, defaults to visual
  visual = "#ff5ef1",
}
M.rainbow_colors = {
  blue = "#5ea1ff",
  green = "#5eff6c",
  cyan = "#5ef1ff",
  red = "#ff6e5e",
  yellow = "#f1ff5e",
  magenta = "#ff5ef1",
  pink = "#ff5ea0",
  orange = "#ffbd5e",
  purple = "#bd5eff",
}

M.layout = {
  select = {
    preview = false,
    layout = {
      backdrop = false,
      row = 0.4,
      width = 0.7,
      min_width = 80,
      height = 0.4,
      min_height = 3,
      box = "vertical",
      border = "rounded",
      title = "{title}",
      title_pos = "center",
      { win = "input", height = 1, border = "bottom" },
      { win = "list", border = "none" },
      { win = "preview", title = "{preview}", height = 0.4, border = "top" },
    },
  },
  dropdown = {
    layout = {
      backdrop = false,
      row = -1,
      min_width = 80,
      -- height = 0.95,
      width = 0.88,
      border = "none",
      box = "vertical",
      { win = "preview", title = "{preview}", height = 0.5, border = "rounded" },
      {
        box = "vertical",
        border = "none",
        title = "{title} {live} {flags}",
        title_pos = "center",
        { win = "input", height = 2, border = "none" },
        { win = "list", border = "none" },
      },
    },
  },
  dropdown_pick = {
    layout = {
      backdrop = false,
      row = -1,
      width = 0.75,
      min_width = 80,
      height = 0.4,
      border = "none",
      box = "vertical",
      -- { win = "preview", title = "{preview}", height = 0.5, border = "single" },
      {
        box = "vertical",
        border = "none",
        title = "{title} {live} {flags}",
        title_pos = "center",
        { win = "input", height = 1, border = "bottom" },
        { win = "list", border = "none" },
      },
    },
  },
  vscode = {
    preview = false,
    layout = {
      backdrop = false,
      row = 0.5,
      width = 0.5,
      min_width = 80,
      height = 0.4,
      border = "none",
      box = "vertical",
      { win = "input", height = 1, border = "bottom" },
      { win = "list", border = "hpad" },
      { win = "preview", title = "{preview}", border = "rounded" },
    },
  },
  mini_pick = {
    layout = {
      box = "vertical",
      backdrop = false,
      row = -1,
      col = 0,
      -- width = 1,
      height = 0.4,
      width = 0.5,
      border = "rounded",
      title = " {title} {live} {flags}",
      title_pos = "left",
      { win = "input", height = 1, border = "bottom" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
      },
    },
  },
  ivy = {
    layout = {
      box = "vertical",
      backdrop = false,
      row = -1,
      -- width = 1,
      height = 0.35,
      border = "none",
      title = " {title} {live} {flags}",
      title_pos = "left",
      { win = "input", height = 1, border = "bottom" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
      },
    },
  },
  ivy_pick = {
    layout = {
      box = "vertical",
      backdrop = false,
      row = 0.6,
      width = 0.8,
      height = 0.4,
      border = "top",
      title = " {title} {live} {flags}",
      title_pos = "left",
      { win = "input", height = 1, border = "bottom" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
      },
    },
  },
  ivy_preview = {
    layout = {
      box = "vertical",
      backdrop = false,
      row = -1,
      width = 0,
      height = 0.4,
      border = "top",
      title = " {title} {live} {flags}",
      title_pos = "left",
      { win = "input", height = 1, border = "bottom" },
      {
        box = "horizontal",
        { win = "list", border = "none" },
        { win = "preview", title = "{preview}", width = 0.5, border = "left" },
      },
    },
  },
  ivy_border = {
    layout = {
      box = "horizontal",
      row = -1,
      width = 0,
      min_width = 120,
      height = 0.4,
      backdrop = false,
      {
        box = "vertical",
        border = "none",
        title = "{title} {live} {flags}",
        { win = "input", height = 1, border = "bottom" },
        { win = "list", border = false },
      },
      { win = "preview", title = "{preview}", border = "rounded", width = 0.5 },
    },
  },
  right = {
    preview = "main",
    layout = {
      backdrop = false,
      width = 40,
      min_width = 40,
      height = 0,
      position = "right",
      border = "none",
      box = "vertical",
      {
        win = "input",
        height = 1,
        border = true,
        title = "{title} {live} {flags}",
        title_pos = "center",
      },
      { win = "list", border = "none" },
      { win = "preview", title = "{preview}", height = 0.4, border = "top" },
    },
  },
}

M.fzf = {
  mini_pick = {
    winopts = {
      height = 0.4, -- window height
      width = 0.65, -- window width
      row = 0.95, -- window row position (0=top, 1=bottom)
      -- col = 0.50, -- window col position (0=left, 1=right)
      border = "none",
      backdrop = 100,
    },
  },
  dropdown = {
    winopts = {
      height = 0.9, -- window height
      -- width = 1, -- window width
      row = 1, -- window row position (0=top, 1=bottom)
      -- col = 0.50, -- window col position (0=left, 1=right)
      border = "none",
      backdrop = 100,
      preview = {
        border = "none",
        wrap = true,
        hidden = false,
        layout = "vertical",
        vertical = "up:50%",
      },
    },
  },
  dropdown_pick = {
    winopts = {
      height = 0.65, -- window height
      width = 0.7, -- window width
      row = 1, -- window row position (0=top, 1=bottom)
      -- col = 0, -- window col position (0=left, 1=right)
      border = "none",
      backdrop = 100,
      preview = {
        border = "rounded",
        wrap = true,
        hidden = false,
        layout = "vertical",
        vertical = "up:50%",
      },
    },
  },
  ivy = {
    winopts = {
      height = 0.35, -- window height
      width = 1, -- window width
      row = 1, -- window row position (0=top, 1=bottom)
      col = 0, -- window col position (0=left, 1=right)
      border = vim.g.bordered and "rounded" or "none",
      backdrop = 100,
      preview = {
        border = "rounded",
        wrap = true,
        hidden = false,
        layout = "horizontal",
        horizontal = "right:45%",
      },
    },
  },
  ivy_pick = {
    winopts = {
      height = 0.4, -- window height
      -- width = 0.7, -- window width
      row = 1, -- window row position (0=top, 1=bottom)
      -- col = 0, -- window col position (0=left, 1=right)
      border = vim.g.bordered and "rounded" or "none",
      backdrop = 100,
      preview = {
        border = "rounded",
        wrap = true,
        hidden = false,
        layout = "horizontal",
        horizontal = "right:50%",
      },
    },
  },
}

M.icons = {
  default_kind_icons = {
    Array = "",
    Boolean = "󰨙",
    Class = "",
    Collapsed = "",
    Color = "",
    Component = "󰅴",
    Constant = "",
    Constructor = "",
    Control = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Fragment = "󰩦",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Macro = "󰁥",
    Method = "",
    Module = "",
    Namespace = "󰦮",
    Null = "",
    Number = "󰎠",
    Object = "",
    Operator = "",
    Package = "",
    Parameter = "",
    Property = "",
    Reference = "",
    Snippet = "",
    StaticMethod = "󰰑",
    String = "",
    Struct = "",
    Text = "",
    TypeAlias = "",
    TypeParameter = "",
    Unit = "",
    Value = "󰎠",
    Variable = "",
  },
  mini_kind_icons = {
    Codeium = "󰚩",
    Copilot = "",
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    Enummember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    ["Function"] = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    Typeparameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  lazy_kind_icons = {
    Array = " ",
    Boolean = "󰨙 ",
    Class = " ",
    Codeium = "󰘦 ",
    Color = " ",
    Control = " ",
    Collapsed = " ",
    Constant = "󰏿 ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = "󰊕 ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = "󰊕 ",
    Module = " ",
    Namespace = "󰦮 ",
    Null = " ",
    Number = "󰎠 ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = "󱄽 ",
    String = " ",
    Struct = "󰆼 ",
    Supermaven = " ",
    TabNine = "󰏚 ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = "󰀫 ",
  },
  lspkind_kind_icons = {
    String = " ",
    Object = " ",
    Array = " ",
    Boolean = "󰨙 ",
    Text = "󰉿",
    Number = "󰎠 ",
    Method = "󰊕",
    Function = "󰊕",
    Constructor = "",
    Field = "󰜢",
    Variable = "󰀫",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Namespace = "󰦮 ",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "󱄽 ",
    Color = "󰏘",
    File = "󰈙",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = " ",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = " ",
    Codeium = "󰚩",
    Copilot = "",
    Control = "",
    Collapsed = "",
    Component = "󰅴",
    Fragment = "󰩦",
    Key = "",
    Macro = "󰁥",
    Null = "",
    Package = "",
    Parameter = "",
    StaticMethod = "󰰑",
    TypeAlias = "",
  },
  codicons = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
    Codeium = "󰚩",
    Copilot = "",
    Control = "",
    Collapsed = "",
    Component = "󰅴",
    Fragment = "󰩦",
    Key = "",
    Macro = "󰁥",
    Null = "",
    Package = "",
    Parameter = "",
    StaticMethod = "󰰑",
    TypeAlias = "",
  },
  misc = {
    dots = "󰇘",
    bug = "",
    dashed_bar = "┊",
    ellipsis = "…",
    git = "",
    palette = "󰏘",
    robot = "󰚩",
    search = "",
    terminal = "",
    toolbox = "󰦬",
    vertical_bar = "│",
  },
  ft = {
    octo = "",
  },
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
}
M.blink = {
  menu = {
    border = {
      { "󱐋", "WarningMsg" },
      "─",
      "╮",
      "│",
      "╯",
      "─",
      "╰",
      "│",
    },
  },
  documention = {
    border = {
      { "", "DiagnosticHint" },
      "─",
      "╮",
      "│",
      "╯",
      "─",
      "╰",
      "│",
    },
  },
}
return M
