

set -gx GH_COPILOT_USE_HELIX_FETCHER true

set -x PATH $PATH $GOPATH/bin
set -x PATH $PATH $HOME/.local/bin
set -x PATH $PATH /opt/homebrew/bin
set -x PATH $PATH /opt/nanobrew/prefix/bin
set -x PATH $PATH $HOME/miniconda3/bin
set -x PATH $PATH $HOME/.local/xonsh-env/bin

# Homebrew generated by `brew shellenv`
set -gx HOMEBREW_PREFIX /opt/homebrew
set -gx HOMEBREW_CELLAR /opt/homebrew/Cellar
set -gx HOMEBREW_REPOSITORY /opt/homebrew
set -q PATH; or set PATH ''
set -gx PATH /opt/homebrew/bin /opt/homebrew/sbin $PATH
set -q MANPATH; or set MANPATH ''
set -gx MANPATH /opt/homebrew/share/man $MANPATH
set -q INFOPATH; or set INFOPATH ''
set -gx INFOPATH /opt/homebrew/share/info $INFOPATH
set -gx HOMEBREW_NO_DOWNLOADS_CONCURRENCY auto


set -gx FZF_DEFAULT_OPTS "
--height=40%
--layout=reverse
--border=none
--info=inline
--prompt='❯ '
--pointer='▶'
--marker='✓'
--cycle
--ansi
--bind ctrl-j:down,ctrl-k:up
"

set -Ux fifc_editor nvim

# eza colorizes file extensions - https://the.exa.website/features/colours
set -x -g EZA_COLORS "gm=33;1"

# Prompt colors
# Use terminal palette color names instead of fixed hex values so fish follows
# the active terminal theme.
set fish_color_normal normal
set fish_color_command brblue --bold
set fish_color_param normal
set fish_color_quote brgreen
set fish_color_redirection brmagenta
set fish_color_end bryellow
set fish_color_error brred --bold
set fish_color_comment brblack --italics
set fish_color_operator brcyan
set fish_color_escape bryellow
set fish_color_autosuggestion brblack
set fish_color_valid_path --underline
set fish_color_cwd brgreen
set fish_color_cwd_root brred
set fish_color_user brcyan
set fish_color_host brblue
set fish_color_host_remote bryellow
set fish_color_status brred
set fish_color_cancel brred --reverse
set fish_color_history_current --bold
set fish_color_match --background=brblack
set fish_color_search_match bryellow --background=brblack
set fish_color_selection normal --bold --background=brblack

set fish_pager_color_completion normal
set fish_pager_color_description brblack
set fish_pager_color_prefix brblue --bold --underline
set fish_pager_color_progress brblack --background=brblack
set fish_pager_color_selected_background --background=brblack

alias python=python3
alias pip=pip3

# Colorize grep output (good for log files) - #cspell:disable
alias grep 'grep --color=auto'
alias egrep 'egrep --color=auto'
alias fgrep 'fgrep --color=auto'

# Confirm before overwriting
alias cp 'cp -Ri'
alias mv 'mv -i'
alias rm 'rm -i'

# Create/delete directories
alias md 'mkdir -p'
alias rd 'rmdir -p'

# Navigation
alias .. 'cd ..'
alias ... 'cd ../..'
alias .... 'cd ../../..'
alias ..... 'cd ../../../..'
alias ...... 'cd ../../../../..'
alias l 'eza --long --all --header --git --icons --no-permissions --no-time --no-user --no-filesize --group-directories-first'
alias ll 'eza -lagh --git --icons --no-user'
alias la 'eza -lagh --git --icons --no-user --sort modified'
alias cll 'clear; and eza --long --all --header --git --icons --no-permissions --no-time --no-user --no-filesize --group-directories-first'

# Tree view
alias tree 'eza -Ta --icons --ignore-glob="node_modules|.git|.vscode|.DS_Store"'
alias ltd 'eza -TaD --icons --ignore-glob="node_modules|.git|.vscode|.DS_Store"'

# Editors and Utilities
alias du dua
alias wget 'wget -c'
alias cat bat

# Network shortcuts/aliases and utilities
alias ip "dig +short myip.opendns.com @resolver1.opendns.com" # dumps [YOUR PUBLIC IP] [URL IP]
alias ipl "ipconfig getifaddr en0" #internal network IP
alias ips "ifconfig -a | grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sed -e 's/inet6* //'"
alias sniff "sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump "sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
alias whois "grc whois" # colorized whois

# SSH and localhost
alias hostfile 'eval sudo $EDITOR /etc/hosts'

alias nvim "~/nvim-macos-arm64/bin/nvim"


zoxide init --cmd cd fish | source
fzf --fish | source
starship init fish | source
atuin init fish | source
mise activate fish | source

# set java env
set -x JAVA_HOME /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
set -x PATH $PATH $JAVA_HOME/bin


# TODO: path and aliases are kinda slow to source. optimize later.

function ssource --description "source most of my dotfiles, useful if making changes and iterating"
    source ~/.config/fish/functions.fish
    source ~/.exports
end

ssource;

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init2.fish 2>/dev/null || :

carapace _carapace | source

# 启用 vi 模式
fish_vi_key_bindings

# bun
set --export BUN_INSTALL "$HOME/.bun"
set --export PATH $BUN_INSTALL/bin $PATH


function fish_title
    set -l cmd $argv[1]
    set -l shell (string replace -r '^.*/' '' (status fish-path))

    if test -n "$cmd"
        echo "$shell | $cmd "(prompt_pwd)
    else
        echo "$shell | "(prompt_pwd)
    end
end
